### ISSUE TITLE
extend dateNormalizer to rewrite localized datetime into ISO

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#1]
Fri Jan 11 14:47:36 2013  -> 2013-01-11 14:47:36+01:00

Please use some common way:
http://docs.oracle.com/javase/1.4.2/docs/api/java/text/SimpleDateFormat.html

Date startDate = null;
Date endDate = null;
try {
    if (validDateStart!= null) startDate = new SimpleDateFormat("MM/dd/yyyy HH:mm", Locale.ENGLISH).parse(validDateStart + " " + validDateStartTime);
    if (validDateEnd!= null) endDate = new SimpleDateFormat("MM/dd/yyyy HH:mm", Locale.ENGLISH).parse(validDateEnd + " " + validDateEndTime);
} catch (ParseException e) {
    e.printStackTrace();
}

Jan Stavel

**Comment by jstavel** [comment]
http://stackoverflow.com/questions/4496359/how-to-parse-date-string-to-date

**Comment by jstavel** [comment]
http://techtracer.com/2007/03/28/convert-date-to-string-and-string-to-date-in-java/

**Comment by jonatansve** [comment]
I have run a few tests and I believe it is working correctly. If there any bugs, we can reopen it.

**Comment by jstavel** [comment]
Thank you, Jonathan.
It is great to close next goal.

Jan Stavel

**Comment by jstavel** [comment]
SHA: 06198b995c70b418e2ecfd99c9461577c47cf201
