### ISSUE TITLE
added tests of SP "version" into all tests

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#13]
Dear Jonathan,
please, rename variable "version" to "version of an extractor" or something similar.
Since there is "version of format" variable at list of SP.

Next, please, add test of this SP into each test.

As I told that you have to run extractor by hand, I was wrong.
Since raw output is generated you do not have to run external extractor anymore.

I hope all extractors say its own version in a raw output.

**Comment by jonatansve** [comment]
This SP is called Version of Extractor and can be found in extractorProperties.xml.

TODO: Normalize all extractor versions to pattern digitdotdigit etc

**Comment by jonatansve** [comment]
https://github.com/Differ-GSOC/differ/commit/e6fcdaa3a093bc4adaa49e0c6de6eb7be2d21ddf

Only kdu_expand left

**Comment by jonatansve** [comment]
https://github.com/Differ-GSOC/differ/commit/d06e4c35a74665a5867a72fd8539e9883064d6b0

New bean fixes kdu_expand. This is finished for the extractors we have tested so far.
