### ISSUE TITLE
add new SP "time of processing"

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#14]
Dear Jonathan,
please, create new SP that comes to "extractorProperties".

It will tell how much time a running of an extractor takes.

You can name as you want. Important is the name is concises and everyone understand easy what the property means.

Thank you,
Jan Stavel

**Comment by jonatansve** [comment]
https://github.com/Differ-GSOC/differ/commit/741d7c894d614831c321c1728ad08aff861603eb

"Elapsed Time of Extraction" is SP.
