### ISSUE TITLE
merge cmdline and web app branched

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#18]
manage the merging.
will be:
- tested by Jonathan, Thomas
- installed by Vasek

Great,
Jan

**Comment by jonatansve** [comment]
Cmd-line application works with resources in differ-common. Waiting for webapp confirmation before we close it.

**Comment by xrosecky** [comment]
Done in 34d5cd5

I commemnted out this section in appCtx-differ-common.xml - I think it should be removed because the same content appears in appCtx-differ-cmdline.xml:

https://github.com/Differ-GSOC/differ/blob/master/differ-common/src/main/resources/appCtx-differ-common.xml#L13
