### ISSUE TITLE
add time of processing property

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#20]
Dear Jonathan,
please, create around advice:
http://static.springsource.org/spring/docs/3.0.x/reference/aop.html#aop-ataspectj-around-advice

around method:
https://github.com/Differ-GSOC/differ/blob/master/differ-common/src/main/java/cz/nkp/differ/compare/metadata/external/ExternalMetadataExtractor.java#L68

It will compute time consumed when calling an extractor.
Thank you,
Jan Stavel

**Comment by jonatansve** [comment]
https://github.com/Differ-GSOC/differ/commit/741d7c894d614831c321c1728ad08aff861603eb
