### ISSUE TITLE
pdf report for cmdline

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#28]
Please use JasperReports to make pdf/html report of results.
I think you can use drep output file of a cmdline application, since it is xml file.

Please, try to create at least basic report. I will extend it more after you end our cooperation.

Use layout similar to text output with using more typographic features that graphic output offers.

Thanks,
Jan Stavel

**Comment by jonatansve** [comment]
Hi Jan,

Before we start this work, it is important to figure out what the input should be. If we go with the drep approach, the web application cannot compute a pdf without having a report sent from cmd-line application right? So perhaps the input to the PDF class should be a common class. Or we implement drep document creation in web application as well. What do you think?

Jonatan

**Comment by jstavel** [comment]
Oh,
you are right.

I hope drep is know even in web app.

So I am not sure.

It must use a structure that is used even in web app.

Regards,
Jan Stavel

2013/9/6 jonatansve notifications@github.com

> Hi Jan,
> 
> Before we start this work, it is important to figure out what the input
> should be. If we go with the drep approach, the web application cannot
> compute a pdf without having a report sent from cmd-line application right?
> So perhaps the input to the PDF class should be a common class. Or we
> implement drep document creation in web application as well. What do you
> think?
> 
> Jonatan
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Differ-GSOC/differ/issues/28#issuecomment-23952070
> .

## 

Jan Stavìl
Pasovice 71,
tel: 733 230 772

**Comment by jonatansve** [comment]
https://github.com/Differ-GSOC/differ/commit/df0b4ae23807efd4b8a2c475c8e09fcc0233ea46
