### ISSUE TITLE
alone png cannot be processed

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#58]
load png file -> Process
no information about progress.

Just "loading bar" appears.

**Comment by xrosecky** [comment]
Can you send me the PNG file?

**Comment by jstavel** [comment]
Hi Vaclav. I have added images into repository.
There are new testing images now. 
We tried to load this file:
https://github.com/Differ-GSOC/differ/blob/master/docs/images/PNG/1002186430_000015%20(IrfanView).png

**Comment by xrosecky** [comment]
Fixed in 98a68317f0ef0fc658105b0fb5d13ce60aec4691.
