### ISSUE TITLE
tiff cannot be proceeded alone

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#59]
load tiff image -> Proceed
just "loading plugin" appears.

No information about extractors.

**Comment by jstavel** [comment]
for anonymous

**Comment by jstavel** [comment]
even for logged user proceed alone image does not work.

**Comment by xrosecky** [comment]
Can you send me the TIFF file?

**Comment by jstavel** [comment]
https://github.com/Differ-GSOC/differ/blob/master/docs/images/TIFF/1002186430_000015.tif

**Comment by xrosecky** [comment]
Fixed in 98a68317f0ef0fc658105b0fb5d13ce60aec4691.
