### ISSUE TITLE
find out significant properties for an image 01.jpg

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#6]
Dear Jonathan,
please, find out all significant properties for this image.

The image is at a directory docs/examples/images_01/01.jpg.

sudgested plan:
- create new test configuration (example image14SignificantProperties.xml)
- copy all significant properties from significantProperties.xml into new test configuration
- run some extractor (for e.g. imagemagick)
- fill values in the test configuration with values that you decide
- IF you are unsure, you can use report in examples examples/images_01/01/01-01-report.txt, but be careful - there can be mistakes in the report

**Comment by jonatansve** [comment]
jpg tests finalized - some properties to be discussed after tests of more images.
