### ISSUE TITLE
new test for image01 and imagemagick

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#7]
Dear Jonathan,
please create test for imagemagick.

An image it will run for is examples/images_01/01.jpg

Thank you,
Jan

**Comment by jonatansve** [comment]
Imagemagick test framework done.

**Comment by jonatansve** [comment]
https://github.com/Differ-GSOC/differ/commit/fcb1d73d001e0a6af923ec99879474177e764b8f
