### ISSUE TITLE
test of djvudump

### ISSUE THREAD

**Issue by jstavel** [Differ-GSOC/differ#9]
One image we have is at a directory images:
https://github.com/Differ-GSOC/differ/blob/master/docs/images/05.djvu

Please try to make test for this image.

Do know be afraid, it will be difficult a little.

Thanks,
Jan Stavel

**Comment by jonatansve** [comment]
https://github.com/Differ-GSOC/differ/commit/13a0f4eece3217770a1f7df45104253ada3db715
